spring:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
  datasource: # update your db server address, port, username, password
    url: jdbc:mysql://localhost:3306/doordash_assessment?serverTimezone=UTC&useSSL=false
    username:
    password:
  http:
    encoding:
      force: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
    properties:
      hibernate:
        generate_statistics: true
    hibernate:
      ddl-auto:create-drop:logging
  level:
    org:
      hibernate: ERROR


process:
  method: db # db, redis